# Generated by Django 6.1.1 on 2026-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_DB',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Bike_no', models.CharField(max_length=15)),
                ('Brand_name', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Licance', models.CharField(max_length=10)),
                ('Address', models.TextField()),
            ],
        ),
    ]
