# Generated by Django 6.1.1 on 2026-10-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMWapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike_db',
            old_name='Licance',
            new_name='Licence',
        ),
    ]
